version: 2
jobs:
  build:
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
       - run: npm install
       - run: git config --global user.email "gurpreet@newput.com"
       - run: git config --global user.name "Gurpreet-Chhabra"
       - run: git remote add heroku https://heroku:$access_token@git.heroku.com/joom-8.git
       - run: npm run build
       - run: git add dist/
       - run: git commit -am "make it better"
       - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master